[package]
name = "cara"
version = "0.6.0"
edition = "2021"

[dependencies]
spin = "0.9.8"
dashu = "0.4.2"

[dependencies.mimalloc]
version = "0.1.37"
default-features = false

[profile.release]
lto = true
opt-level = 3
panic = "abort"
codegen-units = 1
