[package]
name = "cara"
version = "0.6.0"
edition = "2021"

[dependencies]
spin = "0.9.8"

[dependencies.num-bigint]
version = "0.4.6"
default-features = false
features = ["serde","rand"]

[profile.release]
lto = true
opt-level = "z"
panic = "abort"
# strip = "symbols"
codegen-units = 1
debug = true
